/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrajetsRouteImport } from './routes/trajets'
import { Route as PartenaireRouteImport } from './routes/partenaire'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommentCaMarcheRouteImport } from './routes/comment-ca-marche'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'

const TrajetsRoute = TrajetsRouteImport.update({
  id: '/trajets',
  path: '/trajets',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenaireRoute = PartenaireRouteImport.update({
  id: '/partenaire',
  path: '/partenaire',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentCaMarcheRoute = CommentCaMarcheRouteImport.update({
  id: '/comment-ca-marche',
  path: '/comment-ca-marche',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/contact': typeof ContactRoute
  '/partenaire': typeof PartenaireRoute
  '/trajets': typeof TrajetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/contact': typeof ContactRoute
  '/partenaire': typeof PartenaireRoute
  '/trajets': typeof TrajetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/contact': typeof ContactRoute
  '/partenaire': typeof PartenaireRoute
  '/trajets': typeof TrajetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/comment-ca-marche'
    | '/contact'
    | '/partenaire'
    | '/trajets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/comment-ca-marche'
    | '/contact'
    | '/partenaire'
    | '/trajets'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/comment-ca-marche'
    | '/contact'
    | '/partenaire'
    | '/trajets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  CommentCaMarcheRoute: typeof CommentCaMarcheRoute
  ContactRoute: typeof ContactRoute
  PartenaireRoute: typeof PartenaireRoute
  TrajetsRoute: typeof TrajetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trajets': {
      id: '/trajets'
      path: '/trajets'
      fullPath: '/trajets'
      preLoaderRoute: typeof TrajetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaire': {
      id: '/partenaire'
      path: '/partenaire'
      fullPath: '/partenaire'
      preLoaderRoute: typeof PartenaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-ca-marche': {
      id: '/comment-ca-marche'
      path: '/comment-ca-marche'
      fullPath: '/comment-ca-marche'
      preLoaderRoute: typeof CommentCaMarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  CommentCaMarcheRoute: CommentCaMarcheRoute,
  ContactRoute: ContactRoute,
  PartenaireRoute: PartenaireRoute,
  TrajetsRoute: TrajetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
